# Generated by Django 5.2.4 on 2025-08-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0060_profile_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemreport',
            name='is_respond',
            field=models.BooleanField(default=False),
        ),
    ]
